### ISSUE TITLE
Calculations in 00.scf do not converge, resulting in failure to continue training. raise RuntimeError("No system is avaliable") RuntimeError: No system is avaliable

### ISSUE THREAD

**Issue by yycx1111** [deepmodeling/deepks-kit#88]
I am using deepks for multi-label training. In the log.data in the 00.scf for each iter, the computation gradually does not converge, eventually leading to not being able to continue training. In iter.02, there is no configuration in 00.scf that can converge the calculation.  It causes an error in 01.train of iter.02. **Any suggestions for setting and tuning the training parameters?**

This is the error message.
# data_train/group.00 no system.raw, infer meta from data
# data_train/group.00 reset batch size to 0
# ignore empty dataset: data_train/group.00
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/zwj/miniconda3/envs/deepks/lib/python3.12/site-packages/deepks/model/train.py", line 303, in <module>
    cli()
  File "/home/zwj/miniconda3/envs/deepks/lib/python3.12/site-packages/deepks/main.py", line 71, in train_cli
    main(**argdict)
  File "/home/zwj/miniconda3/envs/deepks/lib/python3.12/site-packages/deepks/model/train.py", line 270, in main
    g_reader = GroupReader(train_paths, **data_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zwj/miniconda3/envs/deepks/lib/python3.12/site-packages/deepks/model/reader.py", line 207, in __init__
    raise RuntimeError("No system is avaliable")
RuntimeError: No system is avaliable

This is the log.data of iter.init, iter.00,iter.01,iter.02.
![Image](https://github.com/user-attachments/assets/78023a5f-7b2e-4b94-8a46-dc0a4e713d0c)
![Image](https://github.com/user-attachments/assets/123a5b04-cd28-4af8-84cd-7a78aacee876)
![Image](https://github.com/user-attachments/assets/8fbef473-0ae7-406a-bef5-d1408973f606)
![Image](https://github.com/user-attachments/assets/b206ad97-25dc-4fb3-bb93-f08dfc821103)

**Comment by ErjieWu** [comment]
Have you ever tried to follow the setting suggested by the official doc

![Image](https://github.com/user-attachments/assets/0ad11621-2b24-4e92-9201-48f16ae02762)

**Comment by yycx1111** [comment]
> Have you ever tried to follow the setting suggested by the official doc
> 
> ![Image](https://github.com/user-attachments/assets/0ad11621-2b24-4e92-9201-48f16ae02762)

No, I have not followed the setting before. I'm testing based on the setting suggested by the official doc now and waiting for the results.

**Comment by yycx1111** [comment]
> Have you ever tried to follow the setting suggested by the official doc
> 
> ![Image](https://github.com/user-attachments/assets/0ad11621-2b24-4e92-9201-48f16ae02762)

After following the official doc settings in init_train, the following error occurs in 01.train

**Comment by yycx1111** [comment]
> Have you ever tried to follow the setting suggested by the official doc
> 
> ![Image](https://github.com/user-attachments/assets/0ad11621-2b24-4e92-9201-48f16ae02762)

After following the official doc settings in init_train, the following error occurs in 01.train. How to solve this error to start training?

# data_train/group.00 no system.raw, infer meta from data
# data_test/group.01 no system.raw, infer meta from data
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/zwj/miniconda3/envs/deepks/lib/python3.12/site-packages/deepks/model/train.py", line 303, in <module>
    cli()
  File "/home/zwj/miniconda3/envs/deepks/lib/python3.12/site-packages/deepks/main.py", line 71, in train_cli
    main(**argdict)
  File "/home/zwj/miniconda3/envs/deepks/lib/python3.12/site-packages/deepks/model/train.py", line 295, in main
    model = CorrNet(**model_args).double()
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/zwj/miniconda3/envs/deepks/lib/python3.12/site-packages/deepks/model/model.py", line 57, in warpper
    func(self, *args, **kwargs)
  File "/home/zwj/miniconda3/envs/deepks/lib/python3.12/site-packages/deepks/model/model.py", line 254, in __init__
    assert sum(self.shell_sec) == input_dim
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

**Comment by yycx1111** [comment]
> Have you ever tried to follow the setting suggested by the official doc
> 
> ![Image](https://github.com/user-attachments/assets/0ad11621-2b24-4e92-9201-48f16ae02762)

After setting this, the convergence rate improves in the first few rounds of training, but at iter.03, the convergence rate decreases to 0. Is there any experience or advice on this situation please? Here is the log.data of the training, iter.init, iter.00,iter.01,iter.02,iter.03 respectively.
**iter.init**
![Image](https://github.com/user-attachments/assets/2e8d886e-d3d8-4a8b-a658-a68e4beb18f1)
**iter.00**
![Image](https://github.com/user-attachments/assets/f52601dc-a9b8-483b-9d3a-4f982aec31b0)
**iter.01**
![Image](https://github.com/user-attachments/assets/67880800-e727-49c4-9781-02d0b86f732e)
**iter.02**
![Image](https://github.com/user-attachments/assets/212f0599-e60b-4c4b-a14d-3b0cbaad403f)
**iter.03**
![Image](https://github.com/user-attachments/assets/4040af4d-b003-4653-b201-f173fa7334e2)

**Comment by xuan112358** [comment]
@yycx1111 Maybe you can try the following suggestions in order:
1. Try the latest code of deepks-kit. Lately we have fixed a bug for band gap label.
2. Change the factors of force, stress and bandgap to some lower values. I notice that after adding these labels into training, the energy error increases quit a lot.
3. Change the params in scf_abacus.yaml. Like smaller mixing_beta or larger scf_nmax etc.
4. Change the start_lr in params.yaml to lower values in iter.init and after.

**Comment by yycx1111** [comment]
> [@yycx1111](https://github.com/yycx1111) Maybe you can try the following suggestions in order:
> 
> 1. Try the latest code of deepks-kit. Lately we have fixed a bug for band gap label.
> 2. Change the factors of force, stress and bandgap to some lower values. I notice that after adding these labels into training, the energy error increases quit a lot.
> 3. Change the params in scf_abacus.yaml. Like smaller mixing_beta or larger scf_nmax etc.
> 4. Change the start_lr in params.yaml to lower values in iter.init and after.

Thank you for your advice. I will keep trying as you suggested. Is this deepks the latest version please?
deepks                    0.2.dev338+gbf7175b          pypi_0    pypi

**Comment by xuan112358** [comment]
> > [@yycx1111](https://github.com/yycx1111) Maybe you can try the following suggestions in order:
> > 
> > 1. Try the latest code of deepks-kit. Lately we have fixed a bug for band gap label.
> > 2. Change the factors of force, stress and bandgap to some lower values. I notice that after adding these labels into training, the energy error increases quit a lot.
> > 3. Change the params in scf_abacus.yaml. Like smaller mixing_beta or larger scf_nmax etc.
> > 4. Change the start_lr in params.yaml to lower values in iter.init and after.
> 
> Thank you for your advice. I will keep trying as you suggested. Is this deepks the latest version please? deepks 0.2.dev338+gbf7175b pypi_0 pypi

Oh! The bug is fixed in branch deveop of https://github.com/MCresearch/DeePKS-L/tree/develop. We update the code in that repo recently.

**Comment by yycx1111** [comment]
> > > [@yycx1111](https://github.com/yycx1111) Maybe you can try the following suggestions in order:
> > > 
> > > 1. Try the latest code of deepks-kit. Lately we have fixed a bug for band gap label.
> > > 2. Change the factors of force, stress and bandgap to some lower values. I notice that after adding these labels into training, the energy error increases quit a lot.
> > > 3. Change the params in scf_abacus.yaml. Like smaller mixing_beta or larger scf_nmax etc.
> > > 4. Change the start_lr in params.yaml to lower values in iter.init and after.
> > 
> > 
> > Thank you for your advice. I will keep trying as you suggested. Is this deepks the latest version please? deepks 0.2.dev338+gbf7175b pypi_0 pypi
> 
> Oh! The bug is fixed in branch deveop of https://github.com/MCresearch/DeePKS-L/tree/develop. We update the code in that repo recently.

After updating the code, the convergence rate of scf calculation for iter.init, iter.00, iter.01 are able to reach 1. But after that the scf situation of iter is still not good. The current parameter tuning has not yet achieved good results.
When analysing the output file of 01.train, there are some questions. 
1. “test.out” file of real_ene and pred_ene refers to which two energy difference between them, why the real_ene is different for different iter?
2. Is it possible to judge the 00.scf situation of the next round of iter based on the output file of 01.train, because the scf calculation takes a long time. It takes a lot of time to adjust the parameters and then scf calculation. Any suggestion for adjusting parameters?Is there any basis to refer to for adjusting the parameters?
